<definitions name = "GetAll_Service"
   targetNamespace = "http://www.examples.com/wsdl/GetAll_Service.wsdl"
   xmlns = "http://schemas.xmlsoap.org/wsdl/"
   xmlns:soap = "http://schemas.xmlsoap.org/wsdl/soap/"
   xmlns:tns = "http://www.examples.com/wsdl/GetAll_Service.wsdl"
   xmlns:xsd = "http://www.w3.org/2001/XMLSchema">

   <message name = "GetAllRequest">
   </message>
   <message name = "GetAllResponse">
      <part name = "result" type = "xsd:string"/>
   </message>
   <portType name = "Port">
      <operation name = "GetAll">
         <input message = "tns:GetAllRequest"/>
         <output message = "tns:GetAllResponse"/>
      </operation>
   </portType>

   <binding name = "GetAll_Binding" type = "tns:Port">
      <soap:binding style = "rpc" transport = "http://schemas.xmlsoap.org/soap/http"/>
      <operation name = "GetAll">
         <soap:operation soapAction = "GetAll"/>
         <input>
            <soap:body encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/" namespace = "urn:examples:GetAll_Service" use = "encoded"/>
         </input>
         <output>
            <soap:body encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/" namespace = "urn:examples:GetAll_Service" use = "encoded"/>
         </output>
      </operation>
   </binding>

   <service name = "GetAll_Service">
      <documentation>WSDL File to get all cars</documentation>
      <port binding = "tns:GetAll_Binding" name = "Port">
         <soap:address location = "http://www.examples.com/GetAll/" />
      </port>
   </service>

</definitions>

